# Generated by Django 2.0.2 on 2020-01-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLeaveModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('gamil', models.EmailField(max_length=254)),
                ('l_type', models.CharField(max_length=60)),
                ('s_date', models.DateField()),
                ('l_date', models.DateField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
