# Generated by Django 2.0.2 on 2020-01-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleavemodel',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
