# Generated by Django 3.0.3 on 2020-03-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_applyleavemodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyleavemodel',
            old_name='gamil',
            new_name='gmail',
        ),
    ]
