# Generated by Django 2.0.2 on 2019-12-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
